#!/bin/sh

while read -r file; do
  case "$1" in
  "w")
    setbg "$file" &
    ;;
  "c")
    if [ -z "$destdir" ]; then
      destdir="$(zoxide query --list | dmenu -l 5 -i -p "Copy file(s) to where?")"
    fi
    if [ ! -d "$destdir" ]; then
      notify-send "$destdir is not a directory, cancelled."
      exit 1
    fi
    cp -- "$file" "$destdir" &&
      notify-send -i "$(readlink -f "$file")" "$file copied to $destdir." &
    ;;
  "m")
    if [ -z "$destdir" ]; then
      destdir="$(zoxide query --list | dmenu -l 5 -i -p "Move file(s) to where?")"
    fi
    if [ ! -d "$destdir" ]; then
      notify-send "$destdir is not a directory, cancelled."
      exit 1
    fi
    mv -- "$file" "$destdir" &&
      notify-send -i "$(readlink -f "$file")" "$file moved to $destdir." &
    ;;
  "r")
    magick "$file" -rotate 90 "$file"
    ;;
  "R")
    magick "$file" -rotate -90 "$file"
    ;;
  "f")
    magick "$file" -flop "$file"
    ;;
  "y")
    printf "%s" "$file" | tr -d '\n' | xclip -selection clipboard &&
      notify-send "$file copied to clipboard" &
    ;;
  "Y")
    readlink -f "$file" | tr -d '\n' | xclip -selection clipboard &&
      notify-send "$(readlink -f "$file") copied to clipboard" &
    ;;
  "d")
    if [ "$(printf "No\\nYes" | dmenu -i -p "Move $file to trash?")" = "Yes" ]; then
      trash-put -- "$file" && notify-send "$file moved to trash"
    fi
    ;;
  "g")
    ifinstalled gimp && setsid -f gimp "$file"
    ;;
  "i")
    notify-send "File information" "$(mediainfo "$file" | sed "s/[ ]\+:/:/g;s/: /: <b>/;s/$/<\/b>/" | grep "<b>")"
    ;;
  "C")
    xclip -selection clipboard -target image/png "$file" &&
      notify-send "$file has been copied to clipboard." && exit 0
    ;;
  esac
done
